main: main.c
	@clang -Wall -Wextra -Wpedantic -fsanitize=address,undefined -std=c23 main.c -o main -I/home/monish/Documents/cproj/small_c_projects/geometry_maze_game/lib -L/home/monish/Documents/cproj/small_c_projects/geometry_maze_game/lib -lraylib -lm -lX11 

clear:
	@rm main
